portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from portfolio.views import HomePageView

urlpatterns = [
    path('',HomePageView.as_view(),name='home_index'),
    path('websites/', include('websites.urls')),
    path('admin/', admin.site.urls),
]

portfolio/websites/urls.py
from django.urls import path

from . import views

app_name = 'websites'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:business_id>/home/', views.home, name='home'),
    path('<int:business_id>/about/', views.about, name='about'),
    path('<int:business_id>/contact/', views.contact, name='contact'),
]

portfolio/websites/models.py
from django.db import models

class Business(models.Model):
    business_name = models.CharField(max_length=200)
    business_mission = models.CharField(max_length=400)
    business_about = models.CharField(max_length=2000)
    business_colour = models.CharField(max_length=200)
    business_photo = models.CharField(max_length=200)
    
class Service(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=200)
    service_text = models.CharField(max_length=200)
    service_icon = models.CharField(max_length=200)

portfolio/portfolio/views.py
from django.views.generic.base import View
from django.shortcuts import render

from websites.models import Business

class HomePageView(View):
    def get(self, request):
        businesses = {'businesses': Business.objects.all()}
        return render(request, 'websites/index.html', context = businesses)

portfolio/websites/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404

from .models import Business

def index(request):
    businesses = Business.objects.all()
    return render(request, 'websites/index.html', {'businesses': businesses})
    
def home(request, business_id):
    try:
        business = Business.objects.get(pk = business_id)
    except Business.DoesNotExist:
        raise Http404("Business does not exist")
    return render(request, 'websites/home.html', {'business': business})
    
def about(request, business_id):
    response = "This will be the about page of the shop with number %s"
    return HttpResponse(response % business_id)
    
def contact(request, business_id):
    response = "This will be the contact page of the shop with number %s"
    return HttpResponse(response % business_id)

portfolio/websites/templates/websites/base.html
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'websites/base_home.css' %}">

<body>

<div class="header" style="background-color: {{ business.business_colour }};">
    <div class="dropdown">
        <button onclick="myFunction()" class="dropbtn">&#x2630;</button>
        <div id="myDropdown" class="dropdown-content">
            <a href="{% url 'websites:index' %}">home</a>
            <a href="https://pcdl2.pythonanywhere.com">my other Django site</a>
            <a href="https://pluttik.github.io">my CSS/Javascript site</a>
        </div>
    </div>
</div>

<div class="header header-business" style="background-image: url('{% static business.business_photo %}');">
    <div class="centered-text">
        <h1>{{ business.business_name }}</h1>
    </div>
</div>

{% block content %}
{% endblock %}

</body>

<script src="{% static 'websites/base_home.js' %}"></script>

portfolio/websites/templates/websites/home.html
<!--This page shows an instance of a business website, the template lives in templates/websites/-->

{% extends 'websites/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'websites/home.css' %}">

<div class="grid-container">

    {% for service in business.service_set.all %}
    <div class="grid-item">
        <center>
        <div class="grid-item icon_circle" style="background-color: {{ business.business_colour }};">
            <p><b>{{ service.service_name|slice:"0:1" }}</b></p>
        </div>
        <!--img src="{% static service.service_icon %}"/-->
            <p><b>{{ service.service_name }}</b></p>
        <p>{{ service.service_text }}</p>
        </center>
    </div>
    {% endfor %}
</div>

{% endblock %}

portfolio/websites/templates/websites/index.html
<!--This page currently loads from both the portfolio homepage and the homepage of the websites app-->
<!--The template lives in templates/websites/-->

{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'websites/base_home.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'websites/index.css' %}">

<body>

<div class="header" style="background-color: {{ business.business_colour }};">
    <div class="dropdown">
        <button onclick="myFunction()" class="dropbtn">&#x2630;</button>
        <div id="myDropdown" class="dropdown-content">
            <a href="{% url 'websites:index' %}">home</a>
            <a href="https://pcdl2.pythonanywhere.com">my other Django site</a>
            <a href="https://pluttik.github.io">my CSS/Javascript site</a>
        </div>
    </div>
</div>

<link rel="stylesheet" type="text/css" href="{% static 'websites/index.css' %}">

<div class="ul-container">
    <h1>Website generator for small businesses</h1>
    <h2>Small business websites created so far:</h2>
    <br>
    <ul>
    {% for business in businesses %}
        <h2><a href="{% url 'websites:home' business.id %}">{{ business.business_name }}</a></h2>
    {% endfor %}
    </ul>
</div>

</body>

<script src="{% static 'websites/base_home.js' %}"></script>